### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by PrelateZeratul** [lenosisnickerboa/csgosl#77]
Hey,

I downloaded the server on my desktop a few days ago and it works fine till now, however I tried moving it to my laptop, and after launching the application and pressing "start server" nothing will happen, it will jump to the "run" window and nothing else will happen.

I tried removing the files and re-downloading it completely and still having the same issue.

I also tried to check the option "validate install" and it validates and says everything is ok.

I'm having the same problem in the article:
https://github.com/lenosisnickerboa/csgosl/issues/27

I tried the step where it says editing the start server to add notepad, and notepad doesn't open..

I'm running windows 10 on both PC's, fully updated, firewall disabled, and running from the actual file not a shortcut, I also tried running it from CMD with admin privileges

Server still works fine on the desktop, but doesn't work if I move it to the laptop

**Comment by lenosisnickerboa** [comment]
From the "I tried the step where it says editing the start server to add notepad, and notepad doesn't open.." statement it sounds like you're a victim of the infamous "Windows can't start vbs scripts" phenomena. If you google "Windows can't start vbs scripts" there are various solutions to the problem.  

You can try to start csgosl manually without using the .vbs script just to make sure it is actually the .vbs script which causes the problems. 

1. Start csgosl
1. Start the server
1. Go to the console tab and copy the complete command line after "Command:" but start with "server.bat" (skip bin/ part)
1. Start a command promp, cd to the folder where you installed csgosl, then cd into the bin folder and paste the command line you copied and press enter. The csgo server should start now. If it starts you know the only problem is the "Windows can't start vbs scripts".

Try it out and let me know how it works for you.

**Comment by PrelateZeratul** [comment]
Hey man,

Thanks for that...tried the steps and the server worked like a charm

I'll be looking for the fix on windows can't start vbs scripts then :)

Thanks a lot, I've been using this to run LAN parties with my pals, cause the sv_lan 1, and connect method didn't work...but this is actually working great , thanks again.

**Comment by lenosisnickerboa** [comment]
In the next release I will add an alternative way to start csgosl, a simple windows batch file csgosl.bat. This can be used as a workaround for people having problems with .vbs files. If you want a quick workaround simple create a csgosl.bat file in the same directory as csgosl.vbs and paste the following into that file:

@start /min bin\csgoslw.bat %1 %2 %3 %4 %5 %6 %7 %8 %9

**Comment by PrelateZeratul** [comment]
Been trying to fix the not being able to run .vbs so far and no luck..
I tried the method you mentioned of creating a batch file, what it does is it opens the same GUI, but whenever I click "start server" it goes to the "run" window and nothing happens just like it always does on the laptop

I'm content I have an alternate solution which is running it from CMD, but I still have no way to opening the server from the GUI

**Comment by lenosisnickerboa** [comment]
Just one more thing; do you have spaces or some other weird characters in the folder name where you install csgosl? That has caused start problems for other users.

**Comment by PrelateZeratul** [comment]
You're right, removing spaces and hyphen ran the file flawlessly..

I'm having another issue now however, where I or anyone else, can't join the server that I created

**Comment by PrelateZeratul** [comment]
We can log into the game, go to community servers, choose LAN, we will find the server however after selecting it gives a boz for connection saying server is not responding

After that it will show loading screen for a few seconds then return to main menu...happens even on the same PC I'm running the server from

Tried disabling firewall and defender without luck

**Comment by lenosisnickerboa** [comment]
Good to hear the first issue was resolved. It's a bit weird that sone have
problems with spaces in folder names, I don't, run all servers in folders
with spaces to find bugs. Apparently haven't found all yet.

To your next problem, can you see anything in the server console window?
Could give a clue at least to what's going on.

Den 19 mars 2017 12:51 em skrev "PrelateZeratul" <notifications@github.com>:

**Comment by PrelateZeratul** [comment]
I can see now that the console srds window is showing lots of errors, maybe that's what's causing this...

I have reset everything to default, and I have upgraded to the new 1.6 and still having the same errors
[SRDS.txt](https://github.com/lenosisnickerboa/csgosl/files/853622/SRDS.txt)

**Comment by lenosisnickerboa** [comment]
Hi again, sorry forgot this thread. No, can't see anything related to not being able to connect. There are no messages in the server console stating it has rejected a connection so it seems the server never even sees the connect request from the game clients. Weird, I don't know what happens. Please let me know if you find out what the problem was.
